version: '3'
services:
  ccs-app:
    image: ryoshino/ccsmark_consumer
    ports:
      - "8090:8090"
    depends_on:
      - docker-postgres
  docker-postgres:
    image: postgres:9.4
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres